import { Inter } from "next/font/google";
import "./globals.css";
import 'material-symbols';
const inter = Inter({ subsets: ["latin"] });
import { Toaster, toast } from 'sonner'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
         <Toaster />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
